export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER='LOGOUT_USER';

export const GET_USER_INFO_REQUEST='GET_USER_INFO_REQUEST';
export const GET_USER_INFO_SUCCESS='GET_USER_INFO_SUCCESS';
export const GET_USER_INFO_FAILURE='GET_USER_INFO_FAILURE';
